### ISSUE TITLE
Not able to take incoming calls

### ISSUE THREAD

**Issue by arpio23** [cutie-shell/cutie-wlc#1]
While there is another toplevel open and there is an incoiming call, you can see the the window but it does not response to any touch events. I assume the compositor is passing the touch events to wrong window or is not passing touch events to any window.

**Comment by erikinkinen** [comment]
I wonder if #3 is related to this.

**Comment by arpio23** [comment]
Hmm, it worked lately but not consistent. Sometimes the calling sound stops when accepting the call but have no audio in calls and UI frozen, will need more testing and some logs. Cannot blame on the device, as its working in phosh without any issues.

**Comment by erikinkinen** [comment]
> Hmm, it worked lately but not consistent. Sometimes the calling sound stops when accepting the call but have no audio in calls and UI frozen, will need more testing and some logs. Cannot blame on the device, as its working in phosh without any issues.

Maybe it is a bug in [cutie-ongoing-call](https://github.com/cutie-shell/cutie-ongoing-call)?

**Comment by erikinkinen** [comment]
@arpio23 , I cannot reproduce this at all on `sargo`. Can you check if this still happens to you?

**Comment by erikinkinen** [comment]
Confirmed to be an adaptation issue and not a cutie bug.
