### ISSUE TITLE
Toplevel with parent toplevel not handled.

### ISSUE THREAD

**Issue by arpio23** [cutie-shell/cutie-wlc#3]
Toplevels with a parent toplevel are not handled yet. While the window is opening but it does not receive touch events, seems like its passed to the parent. Its not possible to select any window in appswitcher.

Can be reproduced by running htop in gnome-console and try to close the window. gnome-console opens dialog informing about a running command.

**Comment by erikinkinen** [comment]
https://github.com/cutie-shell/cutie-wlc/commit/14ce0b71017b3d25c21e25115147e28a83589c47 and https://github.com/cutie-shell/cutie-wlc/commit/5ec435403afdbe6597dec5a2f9473ec556658bb7 should fix this. (at least partially)

**Comment by arpio23** [comment]
https://github.com/cutie-shell/cutie-wlc/commit/28e5c9a535aeb1471c11d8079da3439045b38b0d

Tested with gnome-console, when closing the app and have a command still running in console.

**Comment by arpio23** [comment]
I guess its also related to https://github.com/cutie-shell/cutie-wlc/issues/4
This is the progress branch https://github.com/cutie-shell/cutie-wlc/tree/feature/trixie/tl-popup

**Comment by arpio23** [comment]
Oops, its not resolved yet

**Comment by arpio23** [comment]
https://github.com/cutie-shell/cutie-wlc/commit/3f2b9f86ce863f29babbafdc3c280cbb12d7fab3 is a fix for me. We could scale the apps but if its not a mobile device friendly app, find an alternative.
@erikinkinen what you think?

**Comment by arpio23** [comment]
@erikinkinen I rebased the tl-popup branch. With the latest changes we could close this issue. But I would like to have someone else test it.

**Comment by erikinkinen** [comment]
Tested and merged
