### ISSUE TITLE
Screen will only remain on when the Power button is being pressed 

### ISSUE THREAD

**Issue by mathew-dennis** [cutie-shell/cutie-wlc#5]
After boot the device works as expected.but when the device screen is turned of by pressing the power button.it wont turn on with another click.but rather will remain on only during the time it's being pressed.

This issue is seen in redmi note 7 pro(violet)

**Comment by erikinkinen** [comment]
@arpio23 , I wonder how we should approach this as we cannot reproduce the issue. The issue is likely to be a device specific issue, but I honestly do not have any idea how this could happen.

**Comment by mathew-dennis** [comment]
May be I help by getting the logs?

**Comment by erikinkinen** [comment]
> May be I help by getting the logs?

Not many logs are automatically produced of this event. If you can build cutie-wlc, you could add some qDebug() calls to pinpoint the problem.

**Comment by arpio23** [comment]
@mathew-dennis This was not happening earlier? Did start recently? Also run `sudo journalctl -f | grep cutie-wlc` in the terminal. qpa prints sleepDisplay and unsleepDisplay.

Do you test cutie as stand alone installation or you run it on top of phosh?

**Comment by mathew-dennis** [comment]
I downloaded the cutie zip and flashed it recovery.(not on top of phosh)

I don't remember if it happened before

Oke will check in the evening

**Comment by erikinkinen** [comment]
@mathew-dennis , ping.

**Comment by mathew-dennis** [comment]
hi @erikinkinen,  This happens when I press and release the power button
```
droidian@RedmiNote7Pro:~$ sudo journalctl -f | grep cutie-wlc
[sudo] password for droidian: 
Feb 15 13:18:22 RedmiNote7Pro cutie-wlc[7299]: unsleepDisplay
Feb 15 13:18:22 RedmiNote7Pro cutie-wlc[7299]: sleepDisplay
Feb 15 13:18:22 RedmiNote7Pro cutie-wlc[7299]: Cannot open keyboard input device '/dev/input/event6' (No such file or directory)
Feb 15 13:18:22 RedmiNote7Pro cutie-wlc[7299]: Failed to open keyboard device /dev/input/event6
Feb 15 13:18:22 RedmiNote7Pro cutie-wlc[7299]: Swap requested while display is off

```

**Comment by mathew-dennis** [comment]
when pressing the power button the display wakes up with `Feb 15 13:21:31 RedmiNote7Pro cutie-wlc[7299]: unsleepDisplay
`

when i release the power button `Feb 15 13:21:32 RedmiNote7Pro cutie-wlc[7299]: sleepDisplay
Feb 15 13:21:32 RedmiNote7Pro cutie-wlc[7299]: Swap requested while display is off
`
the screen goes off with this log


note : the device is perfectly usable till the first time the screen goes off

**Comment by erikinkinen** [comment]
I think it might be receiving too many keyboard events from the button. What do you think, @arpio23 ?

**Comment by erikinkinen** [comment]
@arpio23 , ping.

**Comment by arpio23** [comment]
@mathew-dennis Its just a wild guess. But can you test it again with batman masked/disabled. Maybe there is a bug in our protocol implementation?

Also output of ```libinput debug-events``` at the same time would be helpful. Just to see how many calls are happen there.

**Comment by mathew-dennis** [comment]
this is the default state of batman 

droidian@RedmiNote7Pro: $ systemctl status batman
○ batman.service - battery management for Linux phones
     Loaded: loaded (/usr/lib/systemd/system/batman.service; enabled; preset: 
enabled)
     Active: inactive (dead)

**Comment by mathew-dennis** [comment]
no change after disabling batman!!!!

**Comment by mathew-dennis** [comment]
event0   KEYBOARD_KEY            +48.358s	KEY_POWER (116) pressed
 event0   KEYBOARD_KEY            +48.483s	KEY_POWER (116) released



the screen turns on with 	KEY_POWER (116) pressed and when i release the key it turns off  with KEY_POWER (116) released

**Comment by mathew-dennis** [comment]
it was due to dirty flashing .works well on the reflash
