### ISSUE TITLE
Make keyboard popup manually.

### ISSUE THREAD

**Issue by arpio23** [cutie-shell/cutie-wlc#8]
Just did a fresh install and in TG there is no way to type in the confirmation code. TG does not emit text input on this page.

I was thinking to do it with bottom corner swipes, left and right. So would work for both left and right handed people?

**Comment by erikinkinen** [comment]
Agreed.

**Comment by erikinkinen** [comment]
This had now been implemented with bottom corner swipes.

Additionally, in Qt5 applications, such as telegram-desktop, the keyboard opens again automatically. This is implemented in [qt5-text-input-v3](https://github.com/cutie-shell/qt5-text-input-v3/).
